# Generated by Django 5.2.6 on 2025-09-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_counter', '0002_counter_is_favorite_counter_name_alter_counter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
